import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync(new URL('../ui/index.html', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../ui/gnome51.css', import.meta.url), 'utf8');
const appUi = fs.readFileSync(new URL('../ui/app.js', import.meta.url), 'utf8');
const workspaceCss = fs.readFileSync(new URL('../ui/workspace-ready.css', import.meta.url), 'utf8');
const workspaceReady = fs.readFileSync(new URL('../ui/workspace-ready.js', import.meta.url), 'utf8');
const brightnessUi = fs.readFileSync(new URL('../ui/brightness.js', import.meta.url), 'utf8');
const bluetoothUi = fs.readFileSync(new URL('../ui/bluetooth.js', import.meta.url), 'utf8');
const powerModeUi = fs.readFileSync(new URL('../ui/power-mode.js', import.meta.url), 'utf8');
const main = fs.readFileSync(new URL('../src-tauri/src/main.rs', import.meta.url), 'utf8');
const brightness = fs.readFileSync(new URL('../src-tauri/src/windows/brightness.rs', import.meta.url), 'utf8');
const bluetooth = fs.readFileSync(new URL('../src-tauri/src/windows/bluetooth.rs', import.meta.url), 'utf8');
const power = fs.readFileSync(new URL('../src-tauri/src/windows/power.rs', import.meta.url), 'utf8');
const cargo = fs.readFileSync(new URL('../src-tauri/Cargo.toml', import.meta.url), 'utf8');

assert.match(html, /styles\.css[\s\S]*adwaita\.css[\s\S]*gnome51\.css[\s\S]*workspace-ready\.css/);
assert.match(html, /app\.js[\s\S]*workspace-ready\.js[\s\S]*brightness\.js[\s\S]*bluetooth\.js[\s\S]*power-mode\.js/);
assert.match(css, /grid-template-columns:\s*repeat\(6,\s*minmax\(96px,\s*1fr\)\)/);
assert.match(css, /grid-template-rows:\s*repeat\(4,\s*minmax\(86px,\s*1fr\)\)/);
assert.match(css, /--gnome-icon-size:\s*64px/);
assert.match(css, /\.dash\s*\{[\s\S]*height:\s*74px/);
assert.match(css, /\.quick-card\s*\{[\s\S]*gap:\s*10px/);
assert.match(css, /\.control-flyout\s*\{[\s\S]*border-radius:\s*20px/);
assert.match(css, /\.control-option\.is-selected/);
assert.match(css, /@keyframes\s+gnome-control-flyout-in/);
assert.match(css, /prefers-reduced-motion:\s*reduce/);
assert.match(css, /\.app-tile:focus-visible/);
assert.match(css, /\.workspace-nav:focus-visible/);
assert.match(css, /\.control-option:focus-visible/);
assert.doesNotMatch(css, /position:\s*fixed/);
assert.doesNotMatch(css, /frame-overlay|fake-caption|explorer\.exe/i);

assert.doesNotMatch(appUi, /Loading workspace/i);
assert.match(appUi, /workspace-preflight/);
assert.match(workspaceReady, /MutationObserver/);
assert.match(workspaceReady, /#activities-content \.loading/);
assert.match(workspaceReady, /workspace-preflight/);
assert.doesNotMatch(workspaceReady, /Loading workspace/i);
assert.match(workspaceCss, /\.workspace-preflight/);
assert.match(workspaceCss, /\.workspace-preflight__frame/);
assert.match(workspaceCss, /prefers-reduced-motion:\s*reduce/);
assert.match(workspaceCss, /animation:\s*none\s*!important/);

assert.match(brightness, /WmiMonitorBrightness/);
assert.match(brightness, /WmiMonitorBrightnessMethods/);
assert.match(brightness, /WmiSetBrightness/);
assert.match(brightness, /ROOT\\\\WMI/);
assert.match(brightness, /nearest_level/);
assert.match(brightnessUi, /get_brightness_status/);
assert.match(brightnessUi, /set_brightness/);
assert.match(brightnessUi, /MutationObserver/);
assert.match(main, /fn get_brightness_status\(\)/);
assert.match(main, /fn set_brightness\([\s\S]*?value:\s*u8,[\s\S]*?\) -> Result<u8, String>/);
assert.match(main, /get_brightness_status,[\s\S]*set_brightness,/);
assert.match(cargo, /wmi\s*=\s*"0\.18\.4"/);
assert.doesNotMatch(brightnessUi, /powershell|cmd\.exe|powercfg|reg\.exe/i);
assert.doesNotMatch(brightness, /powershell|cmd\.exe|powercfg|reg\.exe/i);

assert.match(bluetooth, /Radio::GetRadiosAsync/);
assert.match(bluetooth, /RadioKind::Bluetooth/);
assert.match(bluetooth, /Radio::RequestAccessAsync/);
assert.match(bluetooth, /SetStateAsync/);
assert.match(bluetooth, /RadioAccessStatus::Allowed/);
assert.match(bluetooth, /RoInitialize\(RO_INIT_MULTITHREADED\)/);
assert.match(bluetooth, /RoUninitialize/);
assert.match(bluetoothUi, /get_bluetooth_status/);
assert.match(bluetoothUi, /set_bluetooth_enabled/);
assert.match(bluetoothUi, /control-flyout--bluetooth/);
assert.match(bluetoothUi, /event\.key === 'Escape'/);
assert.match(bluetoothUi, /MutationObserver/);
assert.match(main, /fn get_bluetooth_status\(\)/);
assert.match(main, /fn set_bluetooth_enabled\(enabled:\s*bool\)/);
assert.match(main, /get_bluetooth_status,[\s\S]*set_bluetooth_enabled,/);
assert.match(cargo, /Devices_Radios/);
assert.match(cargo, /Foundation_Collections/);
assert.match(cargo, /Win32_System_WinRT/);
assert.doesNotMatch(bluetoothUi, /powershell|cmd\.exe|reg\.exe|ms-settings:/i);
assert.doesNotMatch(bluetooth, /powershell|cmd\.exe|reg\.exe/i);

assert.match(power, /PowerGetUserConfiguredACPowerMode/);
assert.match(power, /PowerGetUserConfiguredDCPowerMode/);
assert.match(power, /PowerSetUserConfiguredACPowerMode/);
assert.match(power, /PowerSetUserConfiguredDCPowerMode/);
assert.match(power, /GUID_POWER_MODE_BEST_EFFICIENCY/);
assert.match(power, /GUID_POWER_MODE_BEST_PERFORMANCE/);
assert.match(power, /GUID_POWER_MODE_NONE/);
assert.match(power, /pub enum PowerMode/);
assert.match(main, /fn get_power_mode\(\)/);
assert.match(main, /fn set_power_mode\([\s\S]*?mode:\s*String,[\s\S]*?\) -> Result<windows::power::PowerMode, String>/);
assert.match(main, /get_power_mode,[\s\S]*set_power_mode,/);
assert.match(powerModeUi, /get_power_mode/);
assert.match(powerModeUi, /set_power_mode/);
assert.match(powerModeUi, /bestEfficiency/);
assert.match(powerModeUi, /bestPerformance/);
assert.match(powerModeUi, /control-flyout/);
assert.match(powerModeUi, /role="radiogroup"/);
assert.match(powerModeUi, /aria-checked/);
assert.match(powerModeUi, /event\.key === 'Escape'/);
assert.match(powerModeUi, /MutationObserver/);
assert.doesNotMatch(powerModeUi, /powercfg|cmd\.exe|powershell|reg\.exe/i);

console.log('GNOME 51 fidelity contract checks passed');
