import assert from 'node:assert/strict';
import fs from 'node:fs';

const js = fs.readFileSync(new URL('../ui/app.js', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../ui/styles.css', import.meta.url), 'utf8');
const main = fs.readFileSync(new URL('../src-tauri/src/main.rs', import.meta.url), 'utf8');
const frame = fs.readFileSync(new URL('../src-tauri/src/windows/frame.rs', import.meta.url), 'utf8');
const wifi = fs.readFileSync(new URL('../src-tauri/src/windows/wifi.rs', import.meta.url), 'utf8');
const apps = fs.readFileSync(new URL('../src-tauri/src/windows/apps.rs', import.meta.url), 'utf8');
const appbar = fs.readFileSync(new URL('../src-tauri/src/windows/appbar.rs', import.meta.url), 'utf8');
const display = fs.readFileSync(new URL('../src-tauri/src/windows/display.rs', import.meta.url), 'utf8');

assert.match(js, /toggle_activities/);
assert.match(js, /toggle_surface/);
assert.match(js, /list_apps/);
assert.match(js, /list_windows/);
assert.match(js, /launch_app/);
assert.match(js, /terminal/);
assert.match(js, /Show Applications/);
assert.match(js, /calendar-grid/);
assert.match(css, /--accent/);
assert.match(css, /input\[type=range\].*var\(--accent\)/s);
assert.match(css, /grid-template-columns:1fr 1fr/);
assert.match(frame, /DwmSetWindowAttribute/);
assert.doesNotMatch(frame, /GnomeChromeForm|FormBorderStyle|ShowWithoutActivation/);
assert.match(frame, /DWMWA_CAPTION_COLOR/);
assert.match(frame, /DWMWA_TEXT_COLOR/);
assert.match(frame, /DWMWA_COLOR_NONE/);
assert.match(wifi, /WlanSetInterface/);
assert.match(wifi, /WLAN_INTF_OPCODE_RADIO_STATE/);
assert.match(apps, /Get-StartApps/);
assert.match(apps, /windowsterminal|terminal/);
assert.match(appbar, /MonitorFromWindow/);
assert.match(appbar, /GetMonitorInfoW/);
assert.match(appbar, /monitor_info\.monitor\.left/);
assert.match(display, /EnumDisplayMonitors/);
assert.match(display, /GetDpiForMonitor/);
assert.match(display, /MONITORINFOF_PRIMARY/);
assert.match(display, /keeps_negative_desktop_coordinates/);
assert.match(display, /super_ultrawide_geometry_is_not_clamped/);
assert.match(main, /PhysicalPosition/);
assert.match(main, /list_displays/);
assert.doesNotMatch(main, /PhysicalPosition::new\(0,\s*0\)/);
console.log('UI/native contract checks passed');
