import assert from 'node:assert/strict';
import fs from 'node:fs';

const js = fs.readFileSync(new URL('../ui/app.js', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../ui/styles.css', import.meta.url), 'utf8');
const adwaita = fs.readFileSync(new URL('../ui/adwaita.css', import.meta.url), 'utf8');
const main = fs.readFileSync(new URL('../src-tauri/src/main.rs', import.meta.url), 'utf8');
const performance = fs.readFileSync(new URL('../src-tauri/src/performance.rs', import.meta.url), 'utf8');
const layout = fs.readFileSync(new URL('../src-tauri/src/layout.rs', import.meta.url), 'utf8');
const frame = fs.readFileSync(new URL('../src-tauri/src/windows/frame.rs', import.meta.url), 'utf8');
const hotkeys = fs.readFileSync(new URL('../src-tauri/src/windows/hotkeys.rs', import.meta.url), 'utf8');
const panel = fs.readFileSync(new URL('../src-tauri/src/windows/panel.rs', import.meta.url), 'utf8');
const wifi = fs.readFileSync(new URL('../src-tauri/src/windows/wifi.rs', import.meta.url), 'utf8');
const apps = fs.readFileSync(new URL('../src-tauri/src/windows/apps.rs', import.meta.url), 'utf8');
const appbar = fs.readFileSync(new URL('../src-tauri/src/windows/appbar.rs', import.meta.url), 'utf8');
const display = fs.readFileSync(new URL('../src-tauri/src/windows/display.rs', import.meta.url), 'utf8');
const thumbnails = fs.readFileSync(new URL('../src-tauri/src/windows/thumbnails.rs', import.meta.url), 'utf8');
const windowEvents = fs.readFileSync(new URL('../src-tauri/src/windows/window_events.rs', import.meta.url), 'utf8');
const windowsList = fs.readFileSync(new URL('../src-tauri/src/windows/windows_list.rs', import.meta.url), 'utf8');
const virtualDesktop = fs.readFileSync(new URL('../src-tauri/src/windows/virtual_desktop.rs', import.meta.url), 'utf8');
const memorySmoke = fs.readFileSync(new URL('./check-memory-budget.ps1', import.meta.url), 'utf8');
const windowsCi = fs.readFileSync(new URL('../.github/workflows/windows-ci.yml', import.meta.url), 'utf8');

assert.match(js, /toggle_activities/);
assert.match(js, /toggle_surface/);
assert.match(js, /list_apps/);
assert.match(js, /list_windows/);
assert.match(js, /launch_app/);
assert.match(js, /terminal/);
assert.match(js, /Show Applications/);
assert.match(js, /APPS_PER_PAGE = 24/);
assert.match(js, /appSearchScore/);
assert.match(js, /searchApps/);
assert.match(js, /applications-overview/);
assert.match(js, /data-app-page/);
assert.match(js, /dash-favorite/);
assert.match(js, /event\.key === 'Enter'/);
assert.match(js, /event\.key === 'Escape'/);
assert.match(js, /calendar-grid/);
assert.match(js, /captureMode/);
assert.match(js, /captureEvidence/);
assert.match(js, /mark_capture_ready/);
assert.match(js, /nextPaint/);
assert.match(js, /search-terminal/);
assert.match(css, /--accent/);
assert.match(css, /input\[type=range\].*var\(--accent\)/s);
assert.match(css, /grid-template-columns:1fr 1fr/);
assert.match(css, /\.app-pages\{/);
assert.match(css, /grid-template-columns:repeat\(8,minmax\(76px,1fr\)\)/);
assert.match(css, /\.dash-favorite\.is-running::after/);
assert.match(adwaita, /--adw-window-bg:#222226/);
assert.match(adwaita, /--adw-headerbar-bg:#2e2e32/);
assert.match(adwaita, /--adw-overview-bg:#28282c/);
assert.match(adwaita, /\.icon-button\{/);
assert.match(adwaita, /border-radius:50%/);
assert.match(adwaita, /prefers-reduced-motion/);
assert.match(js, /window-card__close/);
assert.match(js, /sync_window_thumbnails/);
assert.match(js, /fedorawin:\/\/windows-changed/);
assert.match(js, /close_window/);
assert.match(js, /onCurrentWorkspace/);
assert.match(js, /detected workspace/);
assert.match(js, /data-workspace-direction/);
assert.match(js, /navigate_workspace/);
assert.match(adwaita, /\.workspace-nav\{/);
assert.match(frame, /DwmSetWindowAttribute/);
assert.doesNotMatch(frame, /GnomeChromeForm|FormBorderStyle|ShowWithoutActivation/);
assert.match(frame, /DWMWA_CAPTION_COLOR/);
assert.match(frame, /DWMWA_TEXT_COLOR/);
assert.match(frame, /DWMWA_COLOR_NONE/);
assert.match(frame, /colorref\(46, 46, 50\)/);
assert.match(frame, /Windows owns the real caption buttons/);
assert.doesNotMatch(windowEvents, /frame_overlay/);
assert.doesNotMatch(main, /frame_overlay/);
assert.match(hotkeys, /RegisterHotKey/);
assert.match(hotkeys, /MOD_ALT \| MOD_NOREPEAT/);
assert.match(hotkeys, /VK_F1/);
assert.match(hotkeys, /toggle_activities/);
assert.match(panel, /CreateWindowExW/);
assert.match(panel, /FedoraWin — panel/);
assert.match(panel, /WS_EX_NOACTIVATE/);
assert.match(panel, /appbar::reserve_top/);
assert.match(panel, /PanelAction::Activities/);
assert.match(panel, /PanelAction::DateMenu/);
assert.match(panel, /PanelAction::QuickSettings/);
assert.match(wifi, /WlanSetInterface/);
assert.match(wifi, /WLAN_INTF_OPCODE_RADIO_STATE/);
assert.match(apps, /Get-StartApps/);
assert.match(apps, /windowsterminal|terminal/);
assert.match(appbar, /MonitorFromWindow/);
assert.match(appbar, /GetMonitorInfoW/);
assert.match(appbar, /monitor_info\.monitor\.left/);
assert.match(display, /EnumDisplayMonitors/);
assert.match(display, /GetDpiForMonitor/);
assert.match(display, /MONITORINFOF_PRIMARY/);
assert.match(display, /topology_signature/);
assert.match(display, /topology_signature_ignores_our_appbar_work_area/);
assert.match(thumbnails, /DwmRegisterThumbnail/);
assert.match(thumbnails, /DwmUpdateThumbnailProperties/);
assert.match(thumbnails, /DwmQueryThumbnailSourceSize/);
assert.match(thumbnails, /source_client_area_only: 1/);
assert.match(windowEvents, /SetWinEventHook/);
assert.match(windowEvents, /WINEVENT_OUTOFCONTEXT \| WINEVENT_SKIPOWNPROCESS/);
assert.match(windowEvents, /GetMessageW/);
assert.match(windowEvents, /fedorawin:\/\/windows-changed/);
assert.match(windowsList, /WM_CLOSE/);
assert.match(windowsList, /PostMessageW/);
assert.match(windowsList, /desktop_id/);
assert.match(windowsList, /on_current_workspace/);
assert.match(windowsList, /DWM_CLOAKED_SHELL/);
assert.match(virtualDesktop, /IVirtualDesktopManager|VirtualDesktopManagerVTable/);
assert.match(virtualDesktop, /GetWindowDesktopId failed/);
assert.match(virtualDesktop, /MoveWindowToDesktop failed/);
assert.match(virtualDesktop, /WorkspaceMoveJournal/);
assert.match(virtualDesktop, /SendInput/);
assert.match(layout, /super_ultrawide_keeps_native_width/);
assert.match(layout, /portrait_display_clamps_large_popovers/);
assert.match(layout, /negative_monitor_origin_is_preserved/);
assert.match(layout, /mixed_dpi_uses_physical_offset_for_panel_height/);
assert.match(main, /PhysicalPosition/);
assert.match(main, /LogicalSize/);
assert.match(main, /list_displays/);
assert.match(main, /get_memory_snapshot/);
assert.match(main, /windows::panel::start/);
assert.match(main, /windows::panel::relayout/);
assert.match(main, /reset_top_level_windows/);
assert.match(main, /RunEvent::Exit/);
assert.match(main, /ensure_shell_surface/);
assert.match(performance, /TARGET_IDLE_MB: u64 = 100/);
assert.match(performance, /HARD_LIMIT_MB: u64 = 300/);
assert.match(performance, /CreateToolhelp32Snapshot/);
assert.match(performance, /GetProcessMemoryInfo/);

assert.match(main, /sync_window_thumbnails/);
assert.match(main, /close_window/);
assert.match(main, /move_window_to_workspace/);
assert.match(main, /undo_workspace_move/);
assert.match(main, /navigate_workspace/);
assert.match(main, /virtual_desktop::navigate/);
assert.match(main, /WorkspaceMoveJournal::default/);
assert.match(main, /window_events::start/);
assert.match(main, /FEDORAWIN_CAPTURE_VIEW/);
assert.match(main, /FEDORAWIN_CAPTURE_THEME/);
assert.match(main, /mark_capture_ready/);
assert.match(main, /— ready/);
assert.match(main, /FedoraWin — \{label\}/);
assert.match(main, /start_display_topology_watcher/);
assert.match(main, /relayout_shell_surfaces/);
assert.doesNotMatch(main, /get_webview_window\("panel"\)/);
assert.match(memorySmoke, /HardLimitMb = 300/);
const captureScript = fs.readFileSync(new URL('./capture-site-preview.ps1', import.meta.url), 'utf8');
assert.match(captureScript, /Assert-VisualCapture/);
assert.match(captureScript, /— ready/);
assert.match(captureScript, /nearWhite/);
assert.match(memorySmoke, /TargetIdleMb = 100/);
assert.match(memorySmoke, /Get-CimInstance Win32_Process/);
assert.match(memorySmoke, /WorkingSet64/);
assert.match(windowsCi, /FedoraWin memory budget/);
assert.match(windowsCi, /check-memory-budget\.ps1/);
assert.doesNotMatch(main, /PhysicalPosition::new\(0,\s*0\)/);
console.log('UI/native contract checks passed');
